global:
  domain: app.coralogix.in
  clusterName: CollectorCtrl-EKS
opentelemetry-cluster-collector:
  presets:
    kubernetesEvents:
      enabled: true
    reduceResourceAttributes:
      enabled: true
    kubernetesResources:
      enabled: false
    fleetManagement:
      enabled: true
      supervisor:
        enabled: false
    clusterMetrics:
      enabled: false
    collectorMetrics:
      enabled: false
    kubernetesApiServerMetrics:
      enabled: false
  distribution: eks
  provider: aws
opentelemetry-agent:
  presets:
    hostEntityEvents:
      enabled: false
    fleetManagement:
      enabled: true
      supervisor:
        enabled: false
    spanMetrics:
      enabled: false
    profilesCollection:
      enabled: false
    transactions:
      enabled: false
    logsCollection:
      enabled: true
      reduceLogAttributes:
        enabled: true
    kubeletMetrics:
      enabled: false
    collectorMetrics:
      enabled: false
    statsdReceiver:
      enabled: false
    hostMetrics:
      enabled: false
    kubernetesExtraMetrics:
      enabled: false
    reduceResourceAttributes:
      enabled: true
    coralogixExporter:
      enabled: true
      privateKey: ${env:CORALOGIX_PRIVATE_KEY}
      pipelines:
      - logs
  targetAllocator:
    enabled: false
  distribution: eks
  provider: aws
opentelemetry-ebpf-profiler:
  presets:
    otlpExporter:
      endpoint: ${env:K8S_NODE_IP}:4317
      pipelines:
      - profiles
      tls:
        insecure: true
      enabled: true
    fleetManagement:
      enabled: true
      supervisor:
        enabled: false
  enabled: false
opentelemetry-ebpf-instrumentation:
  enabled: false
coralogix-operator:
  enabled: false
